### ISSUE TITLE
support text-generation-task models from Huggigface

### ISSUE THREAD

**Issue by behrica** [zmedelis/bosquet#16]
Docu is here:

https://huggingface.co/docs/api-inference/detailed_parameters#text-generation-task

This 'task' seem to match bosques concept of "completion"  best.
If I understand hugging fcase ocrrectly, this would then allow  to use > 14000 models from bosquet:
https://huggingface.co/models?pipeline_tag=text-generation

**Comment by behrica** [comment]
This is adding a simple http/get call.
Ones PR #15  is merged 
and if this gets addressed: https://github.com/zmedelis/bosquet/issues/8#issuecomment-1605397954  (I will do an other PR when PR #15 is in)
I can do a PR for adding huggingface models support

**Comment by zmedelis** [comment]
HF model support should be done via [Text Generation Inference (TGI)](https://huggingface.co/docs/text-generation-inference/index)

**Comment by behrica** [comment]
I think that huggingFace supports 2 APIs now.
The classical one is the "Hosted inference API" documented here:
https://huggingface.co/docs/api-inference/index#hosted-inference-api

There is as well the TGI, documented here:
https://huggingface.co/docs/text-generation-inference/index

I could not see that TGI is **hosted** at HuggingFace. They document self-hosting, via Docker for example.
While the "inference API" is hosted here: (rate limited in free version):
https://api-inference.huggingface.co/models/bert-base-uncased

**Comment by Invertisment** [comment]
> having HF would be great!

Hardcoding models and APIs is not great. I think the better way to approach this is not to load API keys from files. See issue #38

**Comment by zmedelis** [comment]
With the latest commits 'LM studio' hosted HF models are supported. See https://zmedelis.github.io/bosquet/notebook/using_llms/index.html. Also, the 'Mixing models' section at the bottom shows how different models can be used for different steps.
