### ISSUE TITLE
Question: Can I connect to an external service in the middle of the prompt chain?

### ISSUE THREAD

**Issue by ronnyli** [zmedelis/bosquet#27]
I'd like to get a prompt response from an LLM, send it to an API, then send the API response back into the LLM (and possibly repeat). Is that possible with Bosquet?

For example:

1. First prompt: "You are a playwright, write a synopsis for a play"
2. Call out to some external service, for example mechanical turk, to collect opinions about the synopsis
3. Second prompt: "Perform sentiment analysis on the following responses: {{ EXTERNAL SERVICE RESPONSE }}"
4. (back to 1): "Adjust your synopsis based on the feedback"

**Comment by zmedelis** [comment]
It is possible via agents https://github.com/zmedelis/bosquet#agents
Thought support for that is very basic, with only calls to Wikipedia available. You'd need to extend the Tool protocol with  Mechanical Turk implementation https://github.com/zmedelis/bosquet/blob/main/src/bosquet/agent/tool.clj

v0.4 release, sometime in early autumn, is planned to have extended support for this. I'll keep in mind the case you describe to add it in.

**Comment by ronnyli** [comment]
Very cool! And implementing a custom agent looks very straightforward. Awesome!
