### ISSUE TITLE
Llama2’s responses aren’t what Bosquet’s parsing expects

### ISSUE THREAD

**Issue by ash-mcc** [zmedelis/bosquet#42]
### Llama2’s responses aren’t what Bosquet’s parsing _expects_

I’m running Bosquet against a local, small (3.8GB) Llama2 model that is wrapped by an OpenAI API service.
Some of the examples that are bundled with Bosquet, fail with this set-up.
It seems like Llama2's responses aren’t what Bosquet’s parsing expects.

This isn't surprising because: 

1. the responses from this small Llama2 model are often poor; and

1. Bosquet hasn't yet been tweaked to work with Llama2's responses.

#### Example problem
I take the code from `math_generate_code.clj` and run `generate` for `question1`.
The `:answer` in Llama2's response often contains a mixture of postfix and infix.
E.g. `" (+ 40 * (200 - 40))"`
But this problem is probably caused by the poor abilities of this small LLM, i.e. this is (1) above.

#### _Resolution_

And after examining other problems in more detail, I'd say that they're all caused by (1).
And Rupert suggested the same.
So this isn't a Bosquet issue intrinsically.
However, Žygimantas suggested recording this as an issue 
since he might do some work to make Bosquet operate better against Llama2.

#### Aside: Bosquet->Llama2 set-up

I'll outline my `Bosquet->Llama2` set-up in case it helps someone:
* I run an OpenAI API service wrapping a local, 3.8GB Llama2 model:
```
python3 -m llama_cpp.server --model llama-2-7b-chat.ggmlv3.q2_K.gguf
```
* I add these entries into Bosquet's config.edn:
```
    :llama2-openai-api-key       "<needed by Bosquet but not by the OpenAI API service>"
    :llama2-openai-api-endpoint  "http://localhost:8000/v1"
```
  ...seems like Bosquet expects an API key even when the service itself doesn't require it(?).
* And I add these entries to Bosquet's system.edn:
```
   ;; Config for an OpenAI API fronted LLM provided by a local Llama2 based service
   [:llm/openai :provider/llama2] {:api-key            #ref [:config :llama2-openai-api-key]
                                   :api-endpoint       #ref [:config :llama2-openai-api-endpoint]
                                   :impl               :openai}

   ;; Default LLM service to use if this is not specified in the
   ;; `generate` call options
   :llm/default-llm               [:llm/openai :provider/llama2]
```

**Comment by zmedelis** [comment]
@ash-mcc many thanks for posting this. With the latest commits, you can more easily experiment with custom models. Provided you can run LM Studio. The only change needed to run those math examples is this

```clojure
(g/generate prompt
   {:examples examples :question question1}
   {:answer {wkk/service :llm/lmstudio}})
```

Trying Llama2-7b and as you report, the response is completely off. It is not code as instructed in examples. Downloading mistra-metamath to check how this is performing. Although there is not much to be done if the model does not behave as needed, I am looking into the possibility of adding `code` coercion into model params. Just like currently supported: list, json, edn

```
{wkk/output-format    :json
  wkk/model-parameters {:model "gpt-4"}}
```

Maybe I can have `code` that would try to make sure that the response is executable code. Not sure if this is possible but worth exploring a bit.

**Comment by zmedelis** [comment]
Closing this and further output coercion work is planned here #45
