### ISSUE TITLE
Consider support for GitHub Copilot

### ISSUE THREAD

**Issue by FieryCod** [zmedelis/bosquet#49]
Dear author! Many thanks for open-sourcing this very top quality package!

I’m curious if GitHub Copilot support is on your radar? I have an idea to leverage Copilot to iteratively enhance and contribute to the code I’m developing, and it appears to be a perfect fit for the agent. 

Best regards,
Karol

**Comment by zmedelis** [comment]
I have never checked out GH Copilot API, I assume they expose it with something like a `complete(prompt)` endpoint. If so, then adding support for Copilot should not be a hard thing to do.

**Comment by zmedelis** [comment]
Closing this, no plans to work on GH Copilot.
