### ISSUE TITLE
Initial configuarion failure

### ISSUE THREAD

**Issue by FearTheDeer9** [zmedelis/bosquet#52]
I'm trying to use the library for the first time, after creating the secrets and config edns, when trying to import the library as such -
[bosquet.llm :as llm]
 I get the following error message:
; Syntax error compiling at (bosquet/llm.clj:1:1).
; namespace 'bosquet.env' not found
; Evaluation of file core.clj failed: class clojure.lang.Compiler$CompilerException

**Comment by zmedelis** [comment]
Hi, thanks for reporting this.

Is it happening with [2024.02.22](https://github.com/zmedelis/bosquet/releases/tag/v2024.02.22) release, or are you using the latest from git head?

**Comment by lidorcg** [comment]
I experience this with "2024.02.22"

**Comment by zmedelis** [comment]
Please try a new release https://github.com/zmedelis/bosquet/releases/tag/v2024.0808
