### ISSUE TITLE
support vor vector stores ?

### ISSUE THREAD

**Issue by behrica** [zmedelis/bosquet#6]
I was reflecting about the minimal tooling we need to work on larger texts with LLMs.
In my view we need 3 things:

1.  a LLM as such able to do 2 operations "completing " and "create embedding"
2. splitting of texts
3. a vector database wit a least 2 operatins (storing vectors, finding closest vectors to given vector)

1) and 2) we have in bosquet, at least minimal

I am not sure if 3) is existing in the Clojure world. I believe there are some vector database having a java binding, at least Milvus does:
https://github.com/milvus-io/milvus-sdk-java/blob/master/examples/main/java/io/milvus/GeneralExample.java

Ideally bosquet would support various vector databases, maybe via an abstraction
Any thoughts ?

**Comment by behrica** [comment]
This has a Clojure client :
https://github.com/vdaas/vald-client-clj

**Comment by zmedelis** [comment]
I would probably go with Pinecone as the first simple implementation. It has REST API https://docs.pinecone.io/reference/list_indexes/

**Comment by behrica** [comment]
Ok, it has a free hosted edition, which is good enough for testing.

I will probably try to implement a little uses case I have, as depicted above.

I am not sure, if this needs any addition / change to bosquet.

**Comment by zmedelis** [comment]
Thanks for suggesting this and let's see what changes it will require.

But there is a more fundamental question. Does this project tries to be Langchain for Clojure (replicating the whole plethora of functionality vector stores and whatnot) or finds some specific and at least slightly different take on LLM use? Hence the pause in Bosquet development.

**Comment by behrica** [comment]
I think we can close this for know.
I tried some things combining text splitting , vector databases  and the LLMs and it composed nicely, all just being data.
